### ISSUE TITLE
The impact of different patch sizes in grid attention

### ISSUE THREAD

**Issue by morgen-star** [google-research/maxvit#4]

**Comment by vztu** [comment]
That's a great question. However, our main experiment on imagenet-1k at 224x224 resolution didn't allow us to do this experiment. Why? Because our backbone has four stages: (224) -- 56 -- 28 -- 14 -- 7. We don't quite have many choices on the patch-size/grid-size parameter. This is the reason why Swin Transformer only uses window-size=7 as well.

However, if we run experiment on imagenet-1k at 256x256 resolution, we may have several options - {2,4,8}. We haven't done experiment on this bit, unfortunately.
